import { Injectable, NotFoundException, ConflictException, Logger } from '@nestjs/common';
import * as admin from 'firebase-admin';
import { FirebaseService } from '../../config/firebase.service';
import { CreateBillDto, BillFrequency } from './dto/create-bill.dto';
import { UpdateBillDto } from './dto/update-bill.dto';
import { PayOccurrenceDto } from './dto/pay-occurrence.dto';
import { UpdateOccurrenceDto } from './dto/update-occurrence.dto';

@Injectable()
export class BillsService {
  private readonly logger = new Logger(BillsService.name);
  private readonly BILLS = 'finance_bills';
  private readonly OCCURRENCES = 'finance_bill_occurrences';
  private readonly TRANSACTIONS = 'finance_transactions';
  private readonly ACCOUNTS = 'finance_accounts';
  private readonly CATEGORIES = 'finance_categories';

  constructor(private readonly firebaseService: FirebaseService) {}

  private get db() {
    return this.firebaseService.getFirestore();
  }

  private now() {
    return new Date().toISOString();
  }

  private clean(obj: Record<string, any>) {
    return Object.fromEntries(Object.entries(obj).filter(([, v]) => v !== undefined));
  }

  private async assertOwner(collection: string, id: string, userId: string) {
    const doc = await this.db.collection(collection).doc(id).get();
    if (!doc.exists || doc.data()!.userId !== userId) {
      throw new NotFoundException(`${collection}/${id} not found`);
    }
    return { id: doc.id, ...doc.data()! };
  }

  // ─── Bills ──────────────────────────────────────────────────────────────────

  async createBill(userId: string, dto: CreateBillDto) {
    await this.assertOwner(this.ACCOUNTS, dto.accountId, userId);
    await this.assertOwner(this.CATEGORIES, dto.categoryId, userId);
    const data = {
      ...this.clean(dto as any),
      userId,
      isActive: dto.isActive ?? true,
      createdAt: this.now(),
      updatedAt: this.now(),
    };
    const ref = await this.db.collection(this.BILLS).add(data);
    return { id: ref.id, ...data };
  }

  async listBills(userId: string) {
    const snap = await this.db.collection(this.BILLS).where('userId', '==', userId).get();
    return snap.docs
      .map((d) => ({ id: d.id, ...d.data() }))
      .sort((a: any, b: any) => a.name.localeCompare(b.name));
  }

  async updateBill(userId: string, id: string, dto: UpdateBillDto) {
    const existing = await this.assertOwner(this.BILLS, id, userId);
    const updates = { ...this.clean(dto as any), updatedAt: this.now() };
    await this.db.collection(this.BILLS).doc(id).update(updates);
    return { ...existing, ...updates };
  }

  async pauseBill(userId: string, id: string) {
    return this.updateBill(userId, id, { isActive: false } as UpdateBillDto);
  }

  async resumeBill(userId: string, id: string) {
    return this.updateBill(userId, id, { isActive: true } as UpdateBillDto);
  }

  async deleteBill(userId: string, id: string) {
    await this.assertOwner(this.BILLS, id, userId);
    const occSnap = await this.db
      .collection(this.OCCURRENCES)
      .where('userId', '==', userId)
      .where('billId', '==', id)
      .get();
    const batch = this.db.batch();
    for (const doc of occSnap.docs) batch.delete(doc.ref);
    batch.delete(this.db.collection(this.BILLS).doc(id));
    await batch.commit();
    return { message: 'Bill deleted', occurrencesDeleted: occSnap.size };
  }

  // ─── Occurrences ────────────────────────────────────────────────────────────
  //
  // Occurrences are generated by walking a bill's recurrence forward from its
  // last known occurrence (or its startDate, for a bill with none yet) until
  // past the requested range or the bill's endDate. This replaces the old
  // "one occurrence per calendar month, only monthly cadence" generator —
  // weekly/biweekly/custom-interval bills step by days, monthly-and-longer
  // cadences step by months with the due day re-clamped to the target month
  // (so it never drifts) using the bill's own dueDay, never a prior
  // occurrence's day-of-month.

  private addDays(dateStr: string, days: number): string {
    const d = new Date(dateStr + 'T00:00:00');
    d.setDate(d.getDate() + days);
    return d.toISOString().slice(0, 10);
  }

  private addMonthsClamped(dateStr: string, months: number, dueDay: number): string {
    const d = new Date(dateStr + 'T00:00:00');
    const target = new Date(d.getFullYear(), d.getMonth() + months, 1);
    const daysInMonth = new Date(target.getFullYear(), target.getMonth() + 1, 0).getDate();
    const day = Math.min(dueDay, daysInMonth);
    return `${target.getFullYear()}-${String(target.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  }

  private computeNextDueDate(fromDate: string, bill: { frequency: BillFrequency; dueDay: number; interval?: number }): string {
    switch (bill.frequency) {
      case BillFrequency.WEEKLY: return this.addDays(fromDate, 7);
      case BillFrequency.BIWEEKLY: return this.addDays(fromDate, 14);
      case BillFrequency.MONTHLY: return this.addMonthsClamped(fromDate, 1, bill.dueDay);
      case BillFrequency.BIMONTHLY: return this.addMonthsClamped(fromDate, 2, bill.dueDay);
      case BillFrequency.QUARTERLY: return this.addMonthsClamped(fromDate, 3, bill.dueDay);
      case BillFrequency.SEMIANNUAL: return this.addMonthsClamped(fromDate, 6, bill.dueDay);
      case BillFrequency.ANNUAL: return this.addMonthsClamped(fromDate, 12, bill.dueDay);
      case BillFrequency.CUSTOM: return this.addDays(fromDate, Math.max(1, bill.interval ?? 30));
      default: return this.addMonthsClamped(fromDate, 1, bill.dueDay);
    }
  }

  async generateOccurrencesForRange(userId: string, fromDate: string, toDate: string): Promise<void> {
    const billsSnap = await this.db
      .collection(this.BILLS)
      .where('userId', '==', userId)
      .where('isActive', '==', true)
      .get();
    if (billsSnap.empty) return;

    const today = new Date().toISOString().slice(0, 10);
    const bills = billsSnap.docs.map((d) => ({ id: d.id, ...d.data() } as any));

    for (const bill of bills) {
      const occSnap = await this.db
        .collection(this.OCCURRENCES)
        .where('userId', '==', userId)
        .where('billId', '==', bill.id)
        .get();

      const existingDates = new Set<string>();
      let lastDueDate: string | null = null;
      for (const doc of occSnap.docs) {
        const o = doc.data() as any;
        existingDates.add(o.dueDate);
        if (!lastDueDate || o.dueDate > lastDueDate) lastDueDate = o.dueDate;
      }

      let cursor = lastDueDate ? this.computeNextDueDate(lastDueDate, bill) : (bill.startDate as string);
      let guard = 0;
      while (cursor <= toDate && guard < 500) {
        guard++;
        if (bill.endDate && cursor > bill.endDate) break;
        if (cursor >= fromDate && cursor >= bill.startDate && !existingDates.has(cursor)) {
          const status = cursor < today ? 'overdue' : 'pending';
          await this.db.collection(this.OCCURRENCES).add({
            userId,
            billId: bill.id,
            period: cursor.slice(0, 7),
            dueDate: cursor,
            amount: bill.amount,
            status,
            createdAt: this.now(),
            updatedAt: this.now(),
          });
          existingDates.add(cursor);
        }
        cursor = this.computeNextDueDate(cursor, bill);
      }
    }
  }

  private async enrichWithBill(occurrences: any[]) {
    const billIds = [...new Set(occurrences.map((o) => o.billId))];
    const billDocs = await Promise.all(billIds.map((bid) => this.db.collection(this.BILLS).doc(bid).get()));
    const billMap: Record<string, any> = {};
    for (const doc of billDocs) if (doc.exists) billMap[doc.id] = { id: doc.id, ...doc.data() };
    return occurrences.map((o) => ({ ...o, bill: billMap[o.billId] ?? null }));
  }

  async getOccurrences(userId: string, month: string) {
    const start = `${month}-01`;
    const [y, m] = month.split('-').map(Number);
    const end = new Date(Date.UTC(y, m, 0)).toISOString().slice(0, 10);
    await this.generateOccurrencesForRange(userId, start, end);

    const snap = await this.db
      .collection(this.OCCURRENCES)
      .where('userId', '==', userId)
      .where('period', '==', month)
      .get();

    const occurrences = snap.docs.map((d) => ({ id: d.id, ...d.data() })) as any[];
    const enriched = await this.enrichWithBill(occurrences);
    return enriched.sort((a, b) => (a.dueDate < b.dueDate ? -1 : 1));
  }

  async getUpcomingOccurrences(userId: string, days: number) {
    const today = new Date().toISOString().slice(0, 10);
    const toDate = this.addDays(today, days);
    await this.generateOccurrencesForRange(userId, today, toDate);

    // Requires a composite index (userId asc, dueDate asc) — falls back to an
    // in-memory filter if it hasn't been deployed yet.
    let docs: any[];
    try {
      const snap = await this.db
        .collection(this.OCCURRENCES)
        .where('userId', '==', userId)
        .where('dueDate', '<=', toDate)
        .get();
      docs = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
    } catch {
      const snap = await this.db.collection(this.OCCURRENCES).where('userId', '==', userId).get();
      docs = snap.docs.map((d) => ({ id: d.id, ...d.data() })).filter((o: any) => o.dueDate <= toDate);
    }

    const occurrences = (docs as any[])
      .filter((o) => o.status === 'pending' || o.status === 'overdue')
      // Re-derive overdue at read time rather than trusting a status that may be stale.
      .map((o) => ({ ...o, status: o.dueDate < today ? 'overdue' : o.status }));

    const enriched = await this.enrichWithBill(occurrences);
    return enriched.sort((a, b) => (a.dueDate < b.dueDate ? -1 : 1));
  }

  async payOccurrence(userId: string, occurrenceId: string, dto: PayOccurrenceDto) {
    const occurrence: any = await this.assertOwner(this.OCCURRENCES, occurrenceId, userId);
    if (occurrence.status === 'paid') {
      throw new ConflictException('Occurrence is already paid');
    }

    const bill: any = await this.assertOwner(this.BILLS, occurrence.billId, userId);
    await this.assertOwner(this.ACCOUNTS, dto.accountId, userId);

    const txData = {
      userId,
      accountId: dto.accountId,
      categoryId: bill.categoryId,
      amount: dto.amount,
      type: bill.type,
      date: dto.paidAt,
      description: bill.name,
      billOccurrenceId: occurrenceId,
      ...(dto.notes ? { notes: dto.notes } : {}),
      createdAt: this.now(),
      updatedAt: this.now(),
    };

    const txRef = await this.db.collection(this.TRANSACTIONS).add(txData);

    const delta = bill.type === 'income' ? dto.amount : -dto.amount;
    await this.db.collection(this.ACCOUNTS).doc(dto.accountId).update({
      balance: admin.firestore.FieldValue.increment(delta),
      updatedAt: this.now(),
    });

    await this.db.collection(this.OCCURRENCES).doc(occurrenceId).update({
      status: 'paid',
      paidAt: dto.paidAt,
      transactionId: txRef.id,
      paymentAccountId: dto.accountId,
      ...(dto.notes ? { notes: dto.notes } : {}),
      updatedAt: this.now(),
    });

    this.logger.log(`Bill "${bill.name}" occurrence ${occurrenceId} paid → tx ${txRef.id}`);
    return {
      occurrenceId,
      transactionId: txRef.id,
      status: 'paid',
      paidAt: dto.paidAt,
    };
  }

  async updateOccurrence(userId: string, id: string, dto: UpdateOccurrenceDto) {
    const existing = await this.assertOwner(this.OCCURRENCES, id, userId);
    const updates = { ...this.clean(dto as any), updatedAt: this.now() };
    await this.db.collection(this.OCCURRENCES).doc(id).update(updates);
    return { ...existing, ...updates };
  }

  async deleteOccurrence(userId: string, id: string) {
    await this.assertOwner(this.OCCURRENCES, id, userId);
    await this.db.collection(this.OCCURRENCES).doc(id).delete();
    return { message: 'Occurrence deleted' };
  }

  async skipOccurrence(userId: string, id: string) {
    const existing: any = await this.assertOwner(this.OCCURRENCES, id, userId);
    if (existing.status === 'paid') throw new ConflictException('Occurrence is already paid');
    await this.db.collection(this.OCCURRENCES).doc(id).update({ status: 'skipped', updatedAt: this.now() });
    return { message: 'Occurrence skipped' };
  }

  // Called by FinanceService when a transaction created via payOccurrence is
  // deleted — settles the occurrence back to pending rather than leaving it
  // stuck as "paid" with a dangling transactionId.
  async revertOccurrenceToPending(occurrenceId: string) {
    const doc = await this.db.collection(this.OCCURRENCES).doc(occurrenceId).get();
    if (!doc.exists) return;
    await doc.ref.update({
      status: 'pending',
      transactionId: admin.firestore.FieldValue.delete(),
      paymentAccountId: admin.firestore.FieldValue.delete(),
      paidAt: admin.firestore.FieldValue.delete(),
      updatedAt: this.now(),
    });
  }
}
